#include <iostream>
#include <cstdlib>
#include <ctime>

using namespace std;

int main()
{
	char choice = 'y';
	int num; // holding a random number generated by computer
	int guess; // holds the guess of the user
	int numTry = 1; //holds the number of times the user tried
	int difference = 0; // holds the difference between guess and num
	int highScore = 0; // holds the highest score which is the amount of times guessed
	bool isGuessed; // true if user guessed the number correctly

	srand(time(0)); // initialize randomness with time
	num = rand() % 100; // ensure the number is 0 to 100

	isGuessed = false;

	cout << "I have a number between 0 and 100. Try to guess what it is." << endl << endl;

	while (choice != 'n') { // while loop for recursive games
		while (!isGuessed) {
			cout << "So, what is your guess? ";
			cin >> guess;
			difference = guess - num;

			if (guess == num) {
				highScore = numTry;
				cout << "Phew... You got it!!" << endl << endl;
				cout << "You guessed this many times: " << numTry << endl;
				cout << "The current high score is: " << highScore << "\n\n";
				if (highScore < numTry && highScore > 0) {
					highScore = numTry;
					cout << "The new high score is: " << highScore << "\n\n";
				}
				break;
			}

			else if (difference > 50 && difference > 0) {
				cout << "Your guess is way too high, go lower!" << endl << endl;
				numTry++;
			}
			else if (difference < 50 && difference < 0) {
				cout << "Your guess is way too low, go higher!" << endl << endl;
				numTry++;
			}
			else if (difference < 15 && difference > 0) {
				cout << "Your guess is high, but getting closer!" << endl << endl;
				numTry++;
			}
			else if (difference < 15 && difference < 0) {
				cout << "Your guess is low, but getting closer!" << endl << endl;
				numTry++;
			}
			if (numTry == 6) {
				cout << "You have lost the game. You did not guess in 6 tries.\n";
				break;
			}

		}
		cout << "Would you like to play again? <y or n>: ";
		cin >> choice;
		if (choice == 'y') {
			srand(time(0)); // initialize randomness with time
			num = rand() % 100; // ensure the number is 0 to 100
			numTry = 1;
			isGuessed = false;
		}
		else if (choice == 'n') {
			isGuessed = true;
		}
	}
	system("PAUSE");
	return 0;
}
